var canvasWidth = 1200;
var canvasHeight = 400;

var svg1 = d3.select("body").append("svg")
    .attr("width",  canvasWidth)
    .attr("height", canvasHeight)

svg1.append("text")
    .attr("x", "50%")
    .attr("y", "15%")
    .attr("text-anchor", "middle")
    .attr("font-size", "20px")
    .attr("font-family", "sans-serif")
    .attr("font-weight", 200)
    .style("fill", "rgb(0,0,0)")
    .text("Eminem, also known as Marshall Mathers, is widely known to be one of the greatest rapper of all time")

svg1.append("text")
    .attr("x", "50%")
    .attr("y", "22%")
    .attr("text-anchor", "middle")
    .attr("font-size", "20px")
    .attr("font-family", "sans-serif")
    .attr("font-weight", 200)
    .style("fill", "rgb(0,0,0)")
    .text("and is one of the few rappers coming from the 1990’s rap scene still producing and performing. Born")

svg1.append("text")
    .attr("x", "50%")
    .attr("y", "29%")
    .attr("text-anchor", "middle")
    .attr("font-size", "20px")
    .attr("font-family", "sans-serif")
    .attr("font-weight", 200)
    .style("fill", "rgb(0,0,0)")
    .text("in October 17th 1972, Eminem reached up to the top just 3 years after its first home-made album was")

svg1.append("text")
    .attr("x", "50%")
    .attr("y", "36%")
    .attr("text-anchor", "middle")
    .attr("font-size", "20px")
    .attr("font-family", "sans-serif")
    .attr("font-weight", 200)
    .style("fill", "rgb(0,0,0)")
    .text("released, and is now about to turn 50 soon. From the point of view of a huge fan it is hard to see its fa-")

svg1.append("text")
    .attr("x", "50%")
    .attr("y", "43%")
    .attr("text-anchor", "middle")
    .attr("font-size", "20px")
    .attr("font-family", "sans-serif")
    .attr("font-weight", 200)
    .style("fill", "rgb(0,0,0)")
    .text("vorite rapper getting old and the kind of questions one in this situation will likely have running into their")

svg1.append("text")
    .attr("x", "50%")
    .attr("y", "50%")
    .attr("text-anchor", "middle")
    .attr("font-size", "20px")
    .attr("font-family", "sans-serif")
    .attr("font-weight", 200)
    .style("fill", "rgb(0,0,0)")
    .text("mind are: is age affecting Eminem’s style? Its energy? Its danceability? Its productivity?\n")

svg1.append("text")
    .attr("x", "50%")
    .attr("y", "63%")
    .attr("text-anchor", "middle")
    .attr("font-size", "20px")
    .attr("font-family", "sans-serif")
    .attr("font-weight", 200)
    .style("fill", "rgb(0,0,0)")
    .text("And what about its impact on the rap scene? Is it still huge as it was back in time? And if not, what are ")

svg1.append("text")
    .attr("x", "50%")
    .attr("y", "70%")
    .attr("text-anchor", "middle")
    .attr("font-size", "20px")
    .attr("font-family", "sans-serif")
    .attr("font-weight", 200)
    .style("fill", "rgb(0,0,0)")
    .text("the causes that determined such changes? And how those are related to its age? This project, with th")

svg1.append("text")
    .attr("x", "50%")
    .attr("y", "77%")
    .attr("text-anchor", "middle")
    .attr("font-size", "20px")
    .attr("font-family", "sans-serif")
    .attr("font-weight", 200)
    .style("fill", "rgb(0,0,0)")
    .text("e help of a great dataset collected via the Spotify API, aims to provide insights on what could be the a")

svg1.append("text")
    .attr("x", "50%")
    .attr("y", "84%")
    .attr("text-anchor", "middle")
    .attr("font-size", "20px")
    .attr("font-family", "sans-serif")
    .attr("font-weight", 200)
    .style("fill", "rgb(0,0,0)")
    .text("nswers for all those kind of questions.")
